import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Menu from './_components/HamMenu'

import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-stone-800">
        <Menu></Menu>
        {children}
      </body>
    </html>
  );
}


